on:
  push:
    branches:
      - master
    paths-ignore:
      - .github
  pull_request:
    

name: ci-main

env:
  PKI_ROOT_NAME: Test Root CA
  PKI_ROOT_CERT: root.crt
  PKI_ROOT_KEY: root.key
  PKI_ROOT_PASSFILE: root.pass

  PKI_INTER_NAME: Test Intermediate CA
  PKI_INTER_CERT: inter.crt
  PKI_INTER_KEY: inter.key
  PKI_INTER_PASSFILE: inter.pass

  STEP_VERSION: 0.24.2

jobs:
  # Test: generate-root.sh
  test-generate-root:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: echo "7LSV2RJnUhYvNPt3" > $PKI_ROOT_PASSFILE
      - run: bash scripts/generate-root.sh

  # Test: generate-intermediate.sh
  test-generate-intermediate:
    runs-on: [self-hosted, linux, x64]
    needs: ['test-generate-root']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: |
          echo "7LSV2RJnUhYvNPt3" > $PKI_ROOT_PASSFILE
          echo "JTxDhewSepTSQ8gE" > $PKI_INTER_PASSFILE
      - run: |
          bash scripts/generate-root.sh
          bash scripts/generate-intermediate.sh
