on:
  push:
    branches:
      - master
  pull_request:

name: ci-main

env:
  PKI_ROOT_NAME: Test Root CA
  PKI_ROOT_CERT: root.crt
  PKI_ROOT_KEY: root.key
  PKI_ROOT_PASSFILE: root.pass

  PKI_INTERMEDIATE_NAME: Test Intermediate CA
  PKI_INTERMEDIATE_CERT: inter.crt
  PKI_INTERMEDIATE_KEY: inter.key
  PKI_INTERMEDIATE_PASSFILE: inter.pass

  STEP_VERSION: 0.24.2

jobs:
  # Test: generate-root.sh
  test-generate-root:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Create password file
        run: echo "7LSV2RJnUhYvNPt3" > $PKI_ROOT_PASSFILE

      - name: Run script
        run: bash scripts/generate-root.sh

  # Test: generate-intermediate.sh
  test-generate-intermediate:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Create password files
        run: |
          echo "7LSV2RJnUhYvNPt3" > $PKI_ROOT_PASSFILE
          echo "JTxDhewSepTSQ8gE" > $PKI_INTERMEDIATE_PASSFILE

      - name: Run script
        run: |
          bash scripts/generate-root.sh
          bash scripts/generate-intermediate.sh

  # Test: generate-config.sh
  test-generate-config:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Create password files
        run: |
          echo "7LSV2RJnUhYvNPt3" > $PKI_ROOT_PASSFILE
          echo "JTxDhewSepTSQ8gE" > $PKI_INTERMEDIATE_PASSFILE

      - name: Run script
        run: |
          bash scripts/generate-config.sh

  # test-mark:
  #   runs-on: [self-hosted]
  #   needs:
  #     - test-generate-root
  #     - test-generate-intermediate

  