on: [push]
jobs:
  # Generate the `step-ca` ca.json file
  test-generate-root:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          PKI_ROOT_NAME: TestPKI
          PKI_ROOT_CERT: root.cert
          PKI_ROOT_KEY: root.key
          PKI_ROOT_PASSFILE: root.pass
      - run: |
          sudo apt-get update
          wget https://dl.smallstep.com/gh-release/cli/docs-ca-install/v0.24.4/step-cli_0.24.4_amd64.deb
          wget https://dl.smallstep.com/gh-release/cli/docs-ca-install/v0.24.2/step-ca_0.24.2_amd64.deb
          dpkg -i *.deb
          tr -dc A-Za-z0-9 </dev/urandom | head -c 24 > $PKI_ROOT_PASSFILE
      - run: bash scripts/generate-root.sh
