on: [push]
jobs:
  # Generate the `step-ca` ca.json file
  test-generate-root:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          PKI_ROOT_NAME: TestPKI
          PKI_ROOT_CERT: root.cert
          PKI_ROOT_KEY: root.key
          PKI_ROOT_PASSFILE: root.pass
      - run: |
          sudo apt-get update
          sudo apt-get install step step-ca
          tr -dc A-Za-z0-9 </dev/urandom | head -c 24 > $PKI_ROOT_PASSFILE
      - run: bash scripts/generate-root.sh
