on: [push]

name: test-scripts

defaults:
  run:
    shell: bash

jobs:
  # Generate the `step-ca` ca.json file
  test-generate-root:
    runs-on: [self-hosted, linux, x64]
    env:
      PKI_ROOT_NAME: TestPKI
      PKI_ROOT_CERT: root.cert
      PKI_ROOT_KEY: root.key
      PKI_ROOT_PASSFILE: root.pass
      STEP_VERSION: 0.24.2
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: wget "https://dl.smallstep.com/gh-release/cli/docs-ca-install/v""$STEP_VERSION""/step-cli_""$STEP_VERSION""_amd64.deb"
      - run: wget "https://dl.smallstep.com/gh-release/certificates/docs-ca-install/v""$STEP_VERSION""/step-ca_""$STEP_VERSION""_amd64.deb"
      - run: sudo dpkg -i *.deb
      - run: echo "insecure-password" > $PKI_ROOT_PASSFILE
      - run: bash scripts/generate-root.sh
